# beginning pipeline for solid-engine
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  rid: 'linux-x64'

steps:
    - task: UseDotNet@2
      inputs:
        version: '3.1.x'
        packageType: sdk
      
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build $(buildConfiguration)'
      inputs:
        command: 'build'
        projects: |
          $(Agent.BuildDirectory)/s/*.csproj

#deploy to Azure here

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Professional Subscription(bf9e7049-96e4-45d9-be11-a638d2e7c46a)'
    appType: 'webApp'
    WebAppName: 'solid-core'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    
- task: PublishBuildArtifacts@1
    displayName: "Upload Artifacts"
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'solid-engine-artifact'